### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by manbusky** [alibaba-archive/mredis#6]
我尝试使用这样的语句
    var store = mredis.createClient({
        server: ['192.168.0.45:6379', '192.168.0.105:6379'], //redis server addresses
        debug: false,
        speedFirst : true
        pingInterval: 3000,
        reqTimeout: 3000
    });
可是总是报连接不到127.0.0.1:6379的异常！我本地没有装redis server!!
奇了八怪了！！

最后确定，我在['192.168.0.45:6379', '192.168.0.105:6379']上两个服务可以正常单独连接，没有问题！！

**Comment by dead-horse** [comment]
@manbusky 能不能把debug选项打开，然后把输出的信息发来看一下？现在看来是没有连到指定的`redis server`，连到本机去了

**Comment by manbusky** [comment]
是一个  socket.io的问题，如果不是他指定的一个连接 client类型，就自己创建一个了解，传的选项参数里面没有host 和  port 就默认当作了解本机了。。。。
这个项目不支持关于发订阅的命令，所以不支持 socket.io的集群，考虑后面发布新版本吗？

----- Reply message -----
发件人： "dead_horse" notifications@github.com
收件人： "dead-horse/multi_redis" multi_redis@noreply.github.com
抄送： "manbusky" manpusky@gmail.com
主题： [multi_redis] 连接问题  (#6)
日期： 周一, 5 月 20 日, 2013 年 16:57
@manbusky 能不能把debug选项打开，然后把输出的信息发来看一下？现在看来是没有连到指定的redis server，连到本机去了

&mdash;

**Comment by dead-horse** [comment]
嗯，正在考虑支持，因为用socket.io的时候也考虑了这个问题

**Comment by manbusky** [comment]
恩，现在我在做socketio + redis 这方面的集群，你有什么好的建议吗？我挺郁闷的关于这个问题，

2013/5/20 dead_horse notifications@github.com

**Comment by dead-horse** [comment]
`socket.io`的多进程多机房的负载均衡是tpmggip`redis`搞的，`redis`的官方又不支持集群，确实比较蛋疼，在`redis`上有单点。  我们这边也没有在生产上使用过`socket.io`，木有啥生产使用的经验。我看看能不能把`pub/sub`在`mredis`里面支持一下..

**Comment by manbusky** [comment]
redis应该是支持集群的，有master和slave的概念，可以写监控脚本达到切换的作用，
期待你的好消息噢，我现在实现业务，如果你实现了发布订阅功能，我就直接下下来用……

然后修改一下socket.io中的store部分的源代码，让他支持你的mredis的client，

在 2013年5月20日下午11:28，dead_horse notifications@github.com写道：
